### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by doradsoft** [gsioteam/flip_widget#1]
First, thanks for your great job @gsioteam.
Could you please consider adding support for the web platform?
It might be possible using [dart:web-gl](https://api.dart.dev/stable/2.15.1/dart-web_gl/dart-web_gl-library.html) library instead of native code.
If the answer is yes, I would be glad to combine forces and create an enhanced reusable book widget.

**Comment by gsioteam** [comment]
Hi, I have read the document of [dart:web-gl](https://api.dart.dev/stable/2.15.1/dart-web_gl/dart-web_gl-library.html), and try to use it in flutter. But I found maybe it is not a flutter library, maybe I made some mistakes that prevented me from using `dart:web-gl`.

Otherwise, I found the html api maybe a good alternative, [CanvasElement](https://api.dart.dev/stable/2.15.1/dart-html/CanvasElement/getContext3d.html). 

And I don't want to make this plugin too complicated, I use this plugin to implement page flipping effect in [Kinoko](https://github.com/gsioteam/kinoko).

![Untitled](https://user-images.githubusercontent.com/66133807/153877006-32014d48-fe25-4af5-8c65-55e6255a4a2c.gif)

And I think web support is an awesome feature, I will look into how to support. And It would be a huge help if you could point out the mistakes I made with `dart:web-gl`.

**Comment by gsioteam** [comment]
Web support is added in v0.1.7
